/**
 * AUTO-GENERATED FILE. DO NOT EDIT.
 *
 * Generated by: ci-scripts/generate-templates-meta.mjs
 *
 * This file provides a stable TypeScript surface for consumers that import
 * `templates-meta.json`.
 */

export type TemplateDifficulty = 'beginner' | 'intermediate' | 'advanced'

export interface TemplateIntegrity {
  sha256: string
  size: number
}

export interface TemplateSetup {
  packageManager: 'pnpm'
  scripts: Record<string, string>
  env: {
    hasEnvExample: boolean
    hasEnv: boolean
  }
}

export interface TemplateMeta {
  slug: string
  name: string
  title?: string
  version: string
  manifest_version: number
  description: string
  uiContext: string[]
  surfaces: string[]
  entrypoints: string[]
  uiFramework: string
  css: string
  configFiles: string[]
  hasBackground: boolean
  hasEnv: boolean
  setup: TemplateSetup
  permissions: string[]
  host_permissions: string[]
  optional_permissions: string[]
  tags?: string[]
  difficulty?: TemplateDifficulty
  timeToFirstSuccessMinutes?: number
  firstSteps?: string[]
  useCases?: string[]
  docsUrl?: string
  files: string[]
  browsers: string[]
  screenshot: string | null
  icon: string | null
  downloads?: Record<string, string>
  integrity?: Record<string, TemplateIntegrity>
  repositoryUrl?: string
}

export interface TemplatesMetaV2 {
  version: '2'
  sourceRepo: string
  generatorVersion: string
  commit: string
  generatedAt: string
  templates: TemplateMeta[]
}

declare const templatesMeta: TemplatesMetaV2
export default templatesMeta
